# Generated by Django 3.1.6 on 2021-02-13 09:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=3),
            preserve_default=False,
        ),
    ]
