# Generated by Django 3.1.6 on 2021-02-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
