# Generated by Django 3.1.6 on 2021-02-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
