# Generated by Django 3.1.6 on 2021-02-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
